---
- hosts: all
  gather_facts: True
  tasks:
    - name: Display OS distribution and version
      debug:
        msg: "Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"
